# Generated by Django 2.0.2 on 2018-03-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.TextField()),
                ('player2', models.TextField()),
                ('player3', models.TextField()),
                ('player4', models.TextField()),
                ('player5', models.TextField()),
                ('player6', models.TextField()),
                ('player7', models.TextField()),
                ('player8', models.TextField()),
                ('player9', models.TextField()),
                ('player10', models.TextField()),
                ('player11', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bowling_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.TextField()),
                ('player2', models.TextField()),
                ('player3', models.TextField()),
                ('player4', models.TextField()),
                ('player5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=120)),
                ('team2', models.CharField(max_length=120)),
                ('match_type', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('batting1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Batting_log')),
                ('bowling1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Bowling_log')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('fours', models.IntegerField()),
                ('sixs', models.IntegerField()),
                ('matchplayed', models.IntegerField()),
                ('average', models.IntegerField()),
                ('run_rate', models.FloatField()),
                ('HighScore', models.IntegerField()),
                ('overs', models.FloatField()),
                ('wickets', models.IntegerField()),
                ('economy', models.FloatField()),
                ('wicket_streak', models.IntegerField()),
                ('maiden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('player1', models.TextField()),
                ('player2', models.TextField()),
                ('player3', models.TextField()),
                ('player4', models.TextField()),
                ('player5', models.TextField()),
                ('player6', models.TextField()),
                ('player7', models.TextField()),
                ('player8', models.TextField()),
                ('player9', models.TextField()),
                ('player10', models.TextField()),
                ('player11', models.TextField()),
                ('Test_wins', models.IntegerField()),
                ('ODI_wins', models.IntegerField()),
                ('T20_wins', models.IntegerField()),
            ],
        ),
    ]
