# Generated by Django 2.0.2 on 2018-03-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowling2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling2', to='mysite.Bowling_log'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowling1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling1', to='mysite.Bowling_log'),
        ),
    ]
