# Generated by Django 2.0.2 on 2018-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180321_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting_log',
            name='player10',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player11',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player6',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player7',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player8',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='batting_log',
            name='player9',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bowling_log',
            name='player2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bowling_log',
            name='player3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bowling_log',
            name='player4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bowling_log',
            name='player5',
            field=models.TextField(null=True),
        ),
    ]
