# Generated by Django 2.0.2 on 2018-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20180323_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fours',
            new_name='fiftys',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='sixs',
            new_name='hundreds',
        ),
    ]
