# Generated by Django 2.0.2 on 2018-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180323_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Runs',
            field=models.IntegerField(null=True),
        ),
    ]
